// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eTicketing.Catalog.Data;

#nullable disable

namespace eTicketing.Catalog.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260916101220_AddOutboxMessages")]
    partial class AddOutboxMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconBlobName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TicketingMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Koncerti i muzički festivali",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Muzika",
                            TicketingMode = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sportski događaji",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Sport",
                            TicketingMode = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konferencije i meetupovi",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Tehnologija",
                            TicketingMode = 0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("City");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000001"),
                            CategoryId = 1,
                            City = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 15, 20, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trodnevni festival na otvorenom sa regionalnim izvođačima.",
                            Latitude = 43.856299999999997,
                            Longitude = 18.4131,
                            Name = "Ljetni Muzički Festival",
                            OrganizationId = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000002"),
                            CategoryId = 1,
                            City = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 9, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intimni akustični koncert u Vijećnici.",
                            Latitude = 43.856299999999997,
                            Longitude = 18.4131,
                            Name = "Akustična Večer u Vijećnici",
                            OrganizationId = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000003"),
                            CategoryId = 2,
                            City = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 8, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regionalni košarkaški turnir za klupske ekipe.",
                            Latitude = 43.343800000000002,
                            Longitude = 17.8078,
                            Name = "Košarkaški Kup Mostar",
                            OrganizationId = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000004"),
                            CategoryId = 2,
                            City = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 10, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gradski maraton kroz historijsku jezgru Mostara.",
                            Latitude = 43.343800000000002,
                            Longitude = 17.8078,
                            Name = "Maraton Mostar",
                            OrganizationId = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000005"),
                            CategoryId = 3,
                            City = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 11, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Konferencija o softverskom razvoju i startupima.",
                            Latitude = 43.856299999999997,
                            Longitude = 18.4131,
                            Name = "Tech Konferencija Sarajevo",
                            OrganizationId = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3c3c3c3-0000-0000-0000-000000000006"),
                            CategoryId = 3,
                            City = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 11, 20, 18, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Neformalno druženje lokalne startup zajednice.",
                            Latitude = 43.343800000000002,
                            Longitude = 17.8078,
                            Name = "Startup Meetup Mostar",
                            OrganizationId = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            Status = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.RecommendationModelSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InteractionCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingDurationMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("TrainedAt");

                    b.ToTable("RecommendationModelSnapshots");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.UserInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastOccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Type");

                    b.HasIndex("UserId", "ProductId", "Type")
                        .IsUnique();

                    b.ToTable("UserInteractions");
                });

            modelBuilder.Entity("eTicketing.Contracts.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.Product", b =>
                {
                    b.HasOne("eTicketing.Catalog.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("eTicketing.Catalog.Data.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.UserInteraction", b =>
                {
                    b.HasOne("eTicketing.Catalog.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("eTicketing.Catalog.Data.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
